### PR TITLE
fix(gen): properly handle aliased arrays

### LINKED ISSUE #974: gen: optional array fails back to pointer if wrapped
### What version of ogen are you using?

v0.70.1

### Can this issue be reproduced with the latest version?

Yes

### What did you do?

```yaml
openapi: 3.0.3
info:
  title: Object
  version: 1.0.0
paths:
  /object:
    get:
      responses:
        default:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Object'
components:
  schemas:
    Object:
      type: object
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
    Attributes:
      type: array
      items:
        type: number
```

### What did you expect to see?

```go
type Attributes []float64

// Ref: #/components/schemas/Object
type Object struct {
	Attributes Attributes `json:"attributes"`
}
```

### What did you see instead?

```go
type Attributes []float64

// Ref: #/components/schemas/Object
type Object struct {
	Attributes *Attributes `json:"attributes"`
}
```

### PR DESCRIPTION
**Pull request by tdakkota**
Fixes #974

### CODE REVIEW

File: gen/generics.go [hunk 1]
```diff
@@ -60,22 +60,26 @@ func checkStructRecursions(ctx *genctx, s *ir.Type) error {
 }
 
 func boxType(t *ir.Type, v ir.GenericVariant) (*ir.Type, error) {
+	dealised := t
```
Comment (ernado) [inline gen/generics.go:63]: dealiased? 

Should not be confused with dialysis :D

**Review by ernado — APPROVED** [review]
